name: build

on: [push, pull_request]

jobs:
  win-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          mingw-w64-x86_64
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-libusb
          mingw-w64-x86_64-qt5-static
    - name: Build
      shell: msys2 {0}
      run: |
        export PATH="/mingw64/bin:$PATH"
        mkdir build
        cd build
        cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DQt5Widgets_DIR=/mingw64/qt5-static/lib/cmake/Qt5Widgets ..
        make
    - name: Get Zadig
      shell: msys2 {0}
      run: |
        curl -s https://api.github.com/repos/pbatard/libwdi/releases/latest | 
        grep "browser_download_url.*exe" | 
        cut -d : -f 2,3 | 
        tr -d \" | 
        wget -O ./build/bin/zadig.exe -qi -
        rm -fr ./build/bin/heimdall-frontend.exe
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: win-build
        path: "./build/bin/*"

  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install build-essential cmake zlib1g-dev libgl1-mesa-dev libgl1-mesa-glx libusb-1.0-0-dev qt5-default
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: "./build/bin/heimdall"

  macos-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: brew install libusb qt5 cmake
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DQt5Widgets_DIR=/usr/local/opt/qt5/lib/cmake/Qt5Widgets ..
        make
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: "./build/bin/heimdall"
